Repository tiny-nestjs/auto-injectable, pull requests merged in 2023-08, with the labels that each got.

#9 feat: @ComponentScan() dynamic mapping of the path parameter
  .npmignore
  README.md
  package-lock.json
  package.json
  publish-beta
  src/app.module.ts
  src/auto/decorator/component-scan.decorator.ts
  src/lib/auto-injectable.decorator.ts
  src/lib/auto.module.ts
  src/lib/component-scan.decorator.ts
  src/lib/core/importer.spec.ts
  src/lib/core/importer.ts
  src/lib/core/index.ts
  src/lib/decorators/auto-injectable.decorator.spec.ts
  src/lib/decorators/auto-injectable.decorator.ts
  src/lib/decorators/component-scan.decorator.ts
  src/lib/decorators/index.ts
  src/lib/index.ts
  src/lib/interfaces/auto-injectable.constant.ts
  src/lib/interfaces/index.ts
  src/modules/cat/cat.service.ts
  test/fixture.ts
  tsconfig.json
  tsconfig.lib.json
  yarn.lock
Labels: enhancement

#10 chore: shorten import path for lib related stuffs
  README.md
  src/app.controller.ts
  src/app.module.ts
  src/lib/auto.module.ts
  src/lib/core/importer.ts
  src/lib/decorators/auto-injectable.decorator.spec.ts
  src/lib/decorators/auto-injectable.decorator.ts
  src/modules/cat/cat.service.ts
Labels: enhancement

#12 chore: build settings
  package.json
  tsconfig.lib.json
Labels: documentation

#15 fix: lib can be pulled into src
  .eslintrc.js
  jest.config.js
  lib/auto.module.ts
  lib/core/importer.spec.ts
  lib/core/importer.ts
  lib/core/index.ts
  lib/decorators/auto-injectable.decorator.spec.ts
  lib/decorators/auto-injectable.decorator.ts
  lib/decorators/component-scan.decorator.ts
  lib/decorators/index.ts
  lib/index.ts
  lib/interfaces/auto-injectable.constant.ts
  lib/interfaces/index.ts
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  src/modules/cat/cat.interface.ts
  src/modules/cat/cat.service.ts
  test/app.e2e-spec.ts
  test/fixture.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
  tsconfig.lib.json
Labels: enhancement

#17 feat: @AutoController()
  .gitignore
  lib/auto.module.ts
  lib/core/importer.spec.ts
  lib/core/importer.ts
  lib/decorators/auto-controller.decorator.ts
  lib/decorators/auto-injectable.decorator.spec.ts
  lib/interfaces/auto-controller.constant.ts
  lib/interfaces/index.ts
  tsconfig.json
Labels: enhancement

#18 chore: `.prettierrc` set printWidth and tabWidth
  .prettierrc
Labels: enhancement

#19 add: apply husky
  .husky/pre-commit
  lib/core/importer.ts
  lib/decorators/component-scan.decorator.ts
  lib/interfaces/index.ts
  package-lock.json
  package.json
Labels: enhancement

#20 refactor: `Importer`
  README.md
  lib/auto.module.ts
  lib/core/importer.spec.ts
  lib/core/importer.ts
  lib/decorators/auto-controller.decorator.ts
  lib/decorators/auto-injectable.decorator.ts
  lib/decorators/component-scan.decorator.ts
  lib/decorators/index.ts
  package-lock.json
  package.json
Labels: enhancement

#21 feat: `AutoInjectable` can handle alias
  lib/decorators/auto-controller.decorator.ts
  lib/decorators/auto-injectable.decorator.ts
Labels: enhancement

#22 docs: `README.md` for v0.2.1 release
  README.md
  package-lock.json
  package.json
Labels: documentation

#23 release: `v0.2.1`
  .eslintrc.js
  .gitignore
  .husky/pre-commit
  .prettierrc
  README.md
  jest.config.js
  lib/auto.module.ts
  lib/core/importer.spec.ts
  lib/core/importer.ts
  lib/core/index.ts
  lib/decorators/auto-controller.decorator.ts
  lib/decorators/auto-injectable.decorator.spec.ts
  lib/decorators/auto-injectable.decorator.ts
  lib/decorators/component-scan.decorator.ts
  lib/decorators/index.ts
  lib/index.ts
  lib/interfaces/auto-controller.constant.ts
  lib/interfaces/auto-injectable.constant.ts
  lib/interfaces/index.ts
  package-lock.json
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/lib/auto.module.ts
  src/lib/core/importer.spec.ts
  src/lib/core/importer.ts
  src/lib/decorators/auto-injectable.decorator.ts
  src/main.ts
  src/modules/cat/cat.interface.ts
  src/modules/cat/cat.service.ts
  test/app.e2e-spec.ts
  test/fixture.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
  tsconfig.lib.json
Labels: release

#24 release: `v0.2.11`
  README.md
  package-lock.json
  package.json
Labels: documentation, release

#25 release: `v0.2.11`
  README.md
  package-lock.json
  package.json
Labels: release

#26 refactor: auto controller parameter type overloading
  lib/decorators/auto-controller.decorator.ts
Labels: enhancement, good first issue

#28 release: `v0.3.0`
  README.md
  package-lock.json
  package.json
Labels: release, dev

#30 add: `exports` in module
  lib/decorators/component-scan.decorator.ts
Labels: bug, dev

#32 update: `@AutoAlias()` related features, and more.
  README.md
Labels: documentation

#33 fix: getRootGlobPath -> getFolderPath
  lib/core/importer.ts
  lib/decorators/component-scan.decorator.ts
Labels: enhancement

#34 fix: dynamic `@ComponentScan()` parameter
  lib/decorators/component-scan.decorator.ts
Labels: enhancement

#35 add: CODEOWNERS
  .github/CODEOWNERS
Labels: documentation, skip-review

#36 feat: `@ComponentScan` no overlapped range
  .eslintrc.js
  README.md
  lib/core/importer.ts
  lib/decorators/component-scan.decorator.ts
  lib/interfaces/component-scan.constant.ts
  lib/interfaces/index.ts
  package-lock.json
  package.json
Labels: enhancement

#37 release: `v0.3.1`
  .eslintrc.js
  README.md
  lib/auto.module.ts
  lib/core/import-sync.ts
  lib/core/importer.ts
  lib/core/index.ts
  lib/decorators/auto-alias.decorator.ts
  lib/decorators/component-scan.decorator.ts
  lib/decorators/index.ts
  lib/interfaces/auto-alias.constant.ts
  lib/interfaces/component-scan.constant.ts
  lib/interfaces/index.ts
  package-lock.json
  package.json
Labels: release, main

#38 fix: `catchOverlappedScanScope()` error typo (chore)
  README.md
  lib/core/importer.ts
Labels: documentation

#41 fix: duplicate classes / issue #39
  lib/core/importer.ts
Labels: bug
